//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveForWebRIOT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveForWebRIOT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM64 support requires Windows 11..
        /// </summary>
        internal static string Arm64OSRequirement {
            get {
                return ResourceManager.GetString("Arm64OSRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the exported layer..
        /// </summary>
        internal static string DIBLoadFailed {
            get {
                return ResourceManager.GetString("DIBLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Memory..
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIOT.dll was not found in the Effects folder..
        /// </summary>
        internal static string RIOTDllMissing {
            get {
                return ResourceManager.GetString("RIOTDllMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry point &apos;RIOT_LoadFromDIB_U&apos; was not found in RIOT.dll..
        /// </summary>
        internal static string RIOTEntrypointNotFound {
            get {
                return ResourceManager.GetString("RIOTEntrypointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIOT_LoadFromDIB_U returned false..
        /// </summary>
        internal static string RIOTLoadFromDIBFailed {
            get {
                return ResourceManager.GetString("RIOTLoadFromDIBFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIOTProxy.exe is not in the Effects folder..
        /// </summary>
        internal static string RIOTProxyNotFound {
            get {
                return ResourceManager.GetString("RIOTProxyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIOTProxy.exe returned an unexpected exit code 0x{0:X8}..
        /// </summary>
        internal static string UnknownExitCodeFormat {
            get {
                return ResourceManager.GetString("UnknownExitCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} platform is not supported..
        /// </summary>
        internal static string UnsupportedPlatformFormat {
            get {
                return ResourceManager.GetString("UnsupportedPlatformFormat", resourceCulture);
            }
        }
    }
}
